### ISSUE TITLE
Delete Advancement Effect

### ISSUE THREAD

**Issue by AKtomik** [hotpocket184/skript-advancements#3]
hi.
### I have create a custom advancement, but i'd like to **remove it**.

problem : **i dont know any effect wich can make that**.
I speak of an effect who remove the advancement from server files (not the "revoke" effect, who is per player)

> In the GuiThub Wiki : **not**
> In the Skript Hub wiki : **not more**

**If** this expression exist, please **show it** !
**Else**, consider this isse same of a **suggestion** : 
***Can you add an effect to remove any advancement ? Custom advancements first, and if you can, vanilla advancements.***

Thank you for your plugin, it work verry well !
**And thank you in advance for your respond !**

**Comment by hotpocket184** [comment]
I'm currently working on making that effect better than it was previously since it had some issues before. If you would like to delete an advancement before the release of 1.3.2 then I would suggest going into your main world folder in your server, then going to "datapacks", followed by "bukkit" and then "data", then the namespace which would be "skript-advancements" in your case. After entering that folder, you can delete any advancement and then you can reload your server data.

Steps;
`world -> datapacks -> bukkit -> data -> skript-advancements`
